[package]
authors = ["Sebastien Rousseau <sebastian.rousseau@gmail.com>"]
build = "build.rs"
categories = [
    "command-line-utilities",
    "parsing",
    "template-engine",
    "web-programming",
]
description = "A Fast and Flexible Static Site Generator written in Rust."
documentation = "https://lib.rs/crates/ssg"
edition = "2021"
exclude = ["/.git/*", "/.github/*", "/.gitignore", "/.vscode/*"]
homepage = "https://shokunin.one"
keywords = ["cli", "generator", "site", "ssg", "static"]
license = "MIT OR Apache-2.0"
name = "ssg"
readme = "README.md"
repository = "https://github.com/sebastienrousseau/shokunin"
rust-version = "1.68.0"
version = "0.0.7"
include = [
    "/CONTRIBUTING.md",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/benches/**",
    "/build.rs",
    "/Cargo.toml",
    "/content/**",
    "/examples/**",
    "/README.md",
    "/src/**",
    "/template/**",
    "/tests/**",
    "/xtask/**",
]

[workspace]
members = ["xtask"]

# [[bench]]
# name = "benchmark"
# harness = false
# path = "benches/criterion.rs"

# [profile.bench]
# debug = true

[dependencies]
clap = "4.1.11"
comrak = "0.16.0"
reqwest = { version = "0.11.15", features = ["blocking", "json"] }
serde_json = "1.0.94"

[dev-dependencies]
assert_cmd = "2.0.10"
# criterion = "0.4.0"
tempfile = "3.4.0"

[lib]
crate-type = ["lib"]
name = "ssg"
path = "src/lib.rs"

[features]
default = []

[package.metadata.docs.rs]
all-features = true

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = "unwind"
rpath = false
strip = false

[profile.release]
codegen-units = 1        # Compile crates one after another so the compiler can optimize better
debug = false            # Disable debug information
debug-assertions = false # Disable debug assertions
incremental = false      # Disable incremental compilation
lto = true               # Enables link to optimizations
opt-level = "s"          # Optimize for binary size
overflow-checks = false  # Disable overflow checks
panic = "abort"          # Strip expensive panic clean-up logic
rpath = false            # Disable rpath
strip = "symbols"        # Automatically strip symbols from the binary.

[profile.test]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false
strip = false
