+++
"date" = "2023-03-23"
"description" = "Description of the products page"
"keywords" = "products, page, description"
"layout" = "page"
"permalink" = "/products/"
"title" = "Products"
"image" = "https://raw.githubusercontent.com/sebastienrousseau/vault/main/assets/demo/images/logo.min.svg"
+++

This is the products page.
