name: Build
on:
  push:
    branches:
      - 'feat/*'
jobs:
  ssg_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTED=noninteractive
        sudo apt-get -qq update
        sudo apt-get install -y libxkbcommon-dev
    - name: Build ssg binary
      run: cargo build --verbose --package ssg
    - name: Archive ssg binary
      uses: actions/upload-artifact@v1
      with:
        name: ssg-x86_64-unknown-linux-gnu
        path: target/release-opt/ssg
    - name: Pack ssg .deb package
      run: cargo deb --no-build --package ssg
    - name: Rename ssg .deb package
      run: mv target/debian/*.deb target/debian/ssg-x86_64-debian-linux-gnu.deb
    - name: Archive ssg .deb package
      uses: actions/upload-artifact@v1
      with:
        name: ssg-x86_64-debian-linux-gnu
        path: target/debian/ssg-x86_64-debian-linux-gnu.deb

  ssg_windows:
    runs-on: windows-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Enable static CRT linkage
      run: |
        mkdir .cargo
        echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
        echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
    - name: Run the application without starting the shell
      run: |
        sed -i '1 i\#![windows_subsystem = \"windows\"]' examples/ssg/src/main.rs
    - name: Build ssg binary
      run: cargo build --verbose --profile release-opt --package ssg
    - name: Archive ssg binary
      uses: actions/upload-artifact@v1
      with:
        name: ssg-x86_64-pc-windows-msvc
        path: target/release-opt/ssg.exe

  ssg_macos:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Build ssg binary
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
      run: cargo build --verbose --profile release-opt --package ssg
    - name: Open binary via double-click
      run: chmod +x target/release-opt/ssg
    - name: Archive ssg binary
      uses: actions/upload-artifact@v1
      with:
        name: ssg-x86_64-apple-darwin
        path: target/release-opt/ssg

  ssg_raspberry:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@master
    - name: Install cross
      run: cargo install cross
    - name: Build ssg binary for Raspberry Pi 3/4 (64 bits)
      run: cross build --verbose --profile release-opt --package ssg --target aarch64-unknown-linux-gnu
    - name: Archive ssg binary
      uses: actions/upload-artifact@v1
      with:
        name: ssg-aarch64-unknown-linux-gnu
        path: target/aarch64-unknown-linux-gnu/release-opt/ssg
    - name: Build ssg binary for Raspberry Pi 2/3/4 (32 bits)
      run: cross build --verbose --profile release-opt --package ssg --target armv7-unknown-linux-gnueabihf
    - name: Archive ssg binary
      uses: actions/upload-artifact@v1
      with:
        name: ssg-armv7-unknown-linux-gnueabihf
        path: target/armv7-unknown-linux-gnueabihf/release-opt/ssg