name: 🧪 Document
on: [push, pull_request]
jobs:
  all:
    name: Document
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
    steps:

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly

    - uses: actions/checkout@v3

    - name: Update libssl
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1

    - name: Generate documentation for all features and publish it
      run: |
        RUSTDOCFLAGS="--cfg docsrs" \
          cargo doc --no-deps --all-features --workspace

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: target/doc/ssg
        if-no-files-found: error
        retention-days: 1