name: 🧪 Document
on: [push, pull_request]
jobs:
  all:
    name: Document
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
    steps:

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly

    - uses: actions/checkout@v3

    - name: Update libssl
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1

    - name: Generate documentation for all features and publish it
      run: |
        RUSTDOCFLAGS="--cfg docsrs" \
          cargo doc --no-deps --all-features --workspace
          echo 'baseurl: "/ssg"' > ./target/doc/_config.yml

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: target/doc
        if-no-files-found: error
        retention-days: 1

    - name: Write CNAME file
      run: echo 'docs.shokunin.one' > ./target/doc/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        publish_branch: gh-pages
        cname: true
        clean: true
        enable_jekyll: true
        commit_message: Deploy documentation at ${{ github.sha }}
        commit_user_name: github-actions
        commit_user_email: actions@users.noreply.github.com